### ISSUE TITLE
Bug: It is not possible to define a custom font with size -1

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1272]
### Description:

wxWidgets is able to work using a font format like this:
`-1; Default; ; Normal; Normal; Not Underlined`
Where the user is able to change only one property if needed, size too.

But wxUiEditor don't allow the user to insert a size of -1, which means "I want to use the parent font size"
In this example I want to change only the font in order to set BOLD, but the interface doesn't permit to insert -1 in font size.
The same if I use "Default GUI font", I have to define a size even if I don't need it.
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/fce89ee4-d897-43eb-b6ed-e3996c44e04d)

Perhaps I didn't understand, but I think the way currently used in wxUiEditor to define a font should be evaluated for a bit refurbishing.
Couldn't it easier to use the common font definition used in wxWidgets?

**Comment by KeyWorksRW** [comment]
Ah, thanks for raising this issue! There were problems with numeric spin controls which got fixed in one of the point releases of wxWidgets 3.2. wxUiEditor has already picked up that fix, so the spin control needs to be looked at again. I _think_ you can now enter -1, and if not, I think you can now clear the spin control or just enter 0 which could be treated as -1.

**Comment by rossanoparis** [comment]
I've already tried to insert a value 0 or less than 0, but it seems that the minimum is 4 as I highlighted in the picture above.

**Comment by KeyWorksRW** [comment]
That is correct, at the time when I implemented I had to work around the
bug, so I set the minimum size to 4. I *think* it should be possible to now
set the minimum to -1.

**Comment by rossanoparis** [comment]
... I've tried to use the latest daily build, but the limit still persists at 4
